apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-sa
  namespace: default
secrets:
  - name: github-actions-sa-token
---
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-sa-token
  annotations:
    kubernetes.io/service-account.name: github-actions-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-role
  namespace: default
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods", "services", "deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: github-actions-sa
  namespace: default
roleRef:
  kind: Role
  name: github-actions-role
  apiGroup: rbac.authorization.k8s.io
