apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-sa
  namespace: gaming-grids
secrets:
  - name: github-actions-sa-token
---
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-sa-token
  namespace: gaming-grids
  annotations:
    kubernetes.io/service-account.name: github-actions-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-actions-role
  namespace: gaming-grids
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["pods", "services", "deployments", "replicasets", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-rolebinding
  namespace: gaming-grids
subjects:
  - kind: ServiceAccount
    name: github-actions-sa
    namespace: gaming-grids
roleRef:
  kind: ClusterRole
  name: github-actions-role
  apiGroup: rbac.authorization.k8s.io
