apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-ingress
  namespace: gaming-grids
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/issuer: "letsencrypt-prod"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - leaguet.mobyplaygrounds.com
      secretName: leaguet-mobyplaygrounds-tls
  rules:
    - host: leaguet.mobyplaygrounds.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gaming-grids-client
                port:
                  number: 80
